In [1]:
from google.colab import files
uploaded = files.upload()
with open("human_chat.txt", "r", encoding="utf-8") as f:
    faqs = f.read()

Saving human_chat.txt to human_chat.txt


In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

In [3]:
tokenizer = Tokenizer()

In [4]:

tokenizer.fit_on_texts([faqs])

In [5]:
tokenizer.word_index

{'human': 1,
 'i': 2,
 '1': 3,
 '2': 4,
 'you': 5,
 'to': 6,
 'the': 7,
 'a': 8,
 'it': 9,
 'of': 10,
 'and': 11,
 'is': 12,
 'do': 13,
 'that': 14,
 'in': 15,
 'what': 16,
 'for': 17,
 'have': 18,
 'like': 19,
 'are': 20,
 "i'm": 21,
 'but': 22,
 'so': 23,
 'good': 24,
 'about': 25,
 'my': 26,
 "it's": 27,
 'hi': 28,
 'your': 29,
 'how': 30,
 'be': 31,
 'with': 32,
 'not': 33,
 'on': 34,
 'was': 35,
 '🙂': 36,
 'think': 37,
 'going': 38,
 'oh': 39,
 'just': 40,
 'haha': 41,
 'up': 42,
 'this': 43,
 'time': 44,
 'at': 45,
 'we': 46,
 'me': 47,
 'nice': 48,
 'too': 49,
 'some': 50,
 'there': 51,
 'work': 52,
 'very': 53,
 'can': 54,
 'all': 55,
 'really': 56,
 'as': 57,
 'would': 58,
 'day': 59,
 'been': 60,
 'yeah': 61,
 'lot': 62,
 "that's": 63,
 'did': 64,
 'fun': 65,
 'any': 66,
 'great': 67,
 'yes': 68,
 'will': 69,
 'pretty': 70,
 'well': 71,
 'if': 72,
 'out': 73,
 'get': 74,
 'one': 75,
 'know': 76,
 'go': 77,
 'they': 78,
 "don't": 79,
 'or': 80,
 'more': 81,
 'cool': 82,
 'from

In [6]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1, len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])


In [7]:
input_sequences

[[1, 3],
 [1, 3, 28],
 [1, 4],
 [1, 4, 16],
 [1, 4, 16, 12],
 [1, 4, 16, 12, 29],
 [1, 4, 16, 12, 29, 122],
 [1, 4, 16, 12, 29, 122, 311],
 [1, 3],
 [1, 3, 75],
 [1, 3, 75, 90],
 [1, 3, 75, 90, 2],
 [1, 3, 75, 90, 2, 74],
 [1, 3, 75, 90, 2, 74, 6],
 [1, 3, 75, 90, 2, 74, 6, 227],
 [1, 3, 75, 90, 2, 74, 6, 227, 280],
 [1, 3, 75, 90, 2, 74, 6, 227, 280, 10],
 [1, 3, 75, 90, 2, 74, 6, 227, 280, 10, 211],
 [1, 3, 75, 90, 2, 74, 6, 227, 280, 10, 211, 99],
 [1, 4],
 [1, 4, 16],
 [1, 4, 16, 35],
 [1, 4, 16, 35, 7],
 [1, 4, 16, 35, 7, 146],
 [1, 4, 16, 35, 7, 146, 654],
 [1, 4, 16, 35, 7, 146, 654, 10],
 [1, 4, 16, 35, 7, 146, 654, 10, 99],
 [1, 4, 16, 35, 7, 146, 654, 10, 99, 5],
 [1, 4, 16, 35, 7, 146, 654, 10, 99, 5, 18],
 [1, 4, 16, 35, 7, 146, 654, 10, 99, 5, 18, 135],
 [1, 4, 16, 35, 7, 146, 654, 10, 99, 5, 18, 135, 400],
 [1, 4, 16, 35, 7, 146, 654, 10, 99, 5, 18, 135, 400, 262],
 [1, 4, 16, 35, 7, 146, 654, 10, 99, 5, 18, 135, 400, 262, 8],
 [1, 4, 16, 35, 7, 146, 654, 10, 99, 5, 18, 1

In [8]:
max_len =max([len(x) for x in input_sequences])
max_len

153

In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_seq = pad_sequences(input_sequences , maxlen = max_len , padding = 'pre')

In [10]:
padded_input_seq

array([[  0,   0,   0, ...,   0,   1,   3],
       [  0,   0,   0, ...,   1,   3,  28],
       [  0,   0,   0, ...,   0,   1,   4],
       ...,
       [  0,   0,   0, ...,   6,  37,  25],
       [  0,   0,   0, ...,  37,  25, 551],
       [  0,   0,   0, ...,  25, 551,   9]], dtype=int32)

In [11]:
X= padded_input_seq[:, :-1]

In [12]:
y = padded_input_seq[: , -1]
y

array([  3,  28,   4, ...,  25, 551,   9], dtype=int32)

In [13]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y , num_classes = len(tokenizer.word_index) + 1)

In [14]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding , LSTM , Dense

In [16]:
model = Sequential()
model.add(Embedding((len(tokenizer.word_index)+1),100 , input_length =56 ))
model.add(LSTM(150))
model.add(Dense(len(tokenizer.word_index) + 1 , activation = 'softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.compile(loss = 'categorical_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'])

In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.fit(X,y,epochs =50)

Epoch 1/50
659/659 ━━━━━━━━━━━━━━━━━━━━ 156s 237ms/step - accuracy: 0.2580 - loss: 3.5806
Epoch 2/50
659/659 ━━━━━━━━━━━━━━━━━━━━ 154s 233ms/step - accuracy: 0.2779 - loss: 3.4018
Epoch 3/50
659/659 ━━━━━━━━━━━━━━━━━━━━ 153s 231ms/step - accuracy: 0.3075 - loss: 3.1982
Epoch 4/50
659/659 ━━━━━━━━━━━━━━━━━━━━ 154s 234ms/step - accuracy: 0.3420 - loss: 3.0051
Epoch 5/50
659/659 ━━━━━━━━━━━━━━━━━━━━ 156s 237ms/step - accuracy: 0.3791 - loss: 2.8202
Epoch 6/50
659/659 ━━━━━━━━━━━━━━━━━━━━ 198s 231ms/step - accuracy: 0.4082 - loss: 2.6454
Epoch 7/50
659/659 ━━━━━━━━━━━━━━━━━━━━ 203s 233ms/step - accuracy: 0.4429 - loss: 2.4960
Epoch 8/50
659/659 ━━━━━━━━━━━━━━━━━━━━ 157s 238ms/step - accuracy: 0.4725 - loss: 2.3380
Epoch 9/50
659/659 ━━━━━━━━━━━━━━━━━━━━ 154s 233ms/step - accuracy: 0.4958 - loss: 2.2231
Epoch 10/50
659/659 ━━━━━━━━━━━━━━━━━━━━ 202s 232ms/step - accuracy: 0.5238 - loss: 2.0972
Epoch 11/50
659/659 ━━━━━━━━━━━━━━━━━━━━ 205s 237ms/step - accuracy: 0.5458 - loss: 1.9813
Epoch 12

In [27]:
text = 'I am going'
for i in range(5):
  token_text = tokenizer.texts_to_sequences([text])[0]
  padded_token_text = pad_sequences([token_text] , maxlen = 56 , padding = 'pre')
  model.predict(padded_token_text)

  predicted = np.argmax(model.predict(padded_token_text))

  for word , index in tokenizer.word_index.items():
    if index == predicted:
      text = text + ' ' + word
      print(text)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
I am going to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
I am going to diablo
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
I am going to diablo palces
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
I am going to diablo palces before
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
I am going to diablo palces before that
